name: Sync Develop with Master

on:
  push:
    branches:
      - master

jobs:
  sync_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Create or Checkout Develop Branch
        run: |
          if git show-ref --verify --quiet refs/heads/develop; then
            git checkout develop
            git pull origin develop
          else
            git checkout -b develop
          fi

      - name: Merge Master into Develop with conflict resolution
        run: |
          git merge master --no-ff || git merge --strategy-option theirs

      - name: Push Changes to Develop
        run: git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
